name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          user: rohxn-rai
          template: classic

          base: ""
          config_order: languages, achievements
          
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # --- Plugin: Achievements (Replaces your Trophies) ---
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # --- Plugin: IsoCalendar (Optional: Cool 3D contribution view) ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
